platform :ios, '8.0'
use_frameworks!

target 'ReusableDemo' do
  pod 'Reusable', :path => '../'
end

post_install do |installer|
  installer.pods_project.build_configurations.each do |config|
    config.build_settings['SWIFT_VERSION'] = '3.0'
  end
end
