platform :ios, '8.0'
use_frameworks!

target 'ReusableDemo' do
  pod 'Reusable', :path => '../'
end

post_install do |installer|
  target = installer.pods_project.targets.find { |t| t.name.start_with? 'Pods-' }
  target.build_configurations.each do |config|
    config.build_settings['EMBEDDED_CONTENT_CONTAINS_SWIFT'] = 'NO'
  end
end
