defaults:
  - &default-config
    macos:
      xcode: 11.1.0
    shell: /bin/bash --login -eo pipefail
    environment:
      CIRCLE_ARTIFACTS: /tmp/circleci-artifacts
      CIRCLE_TEST_REPORTS: /tmp/circleci-test-results
      BUNDLE_PATH: vendor/bundle
  - &prepare-storage
    run:
      name: Create directories for artifacts and reports
      command: mkdir -p $CIRCLE_ARTIFACTS $CIRCLE_TEST_REPORTS
  - &set-ruby-version
    run:
      name: Set Ruby Version
      command: echo 'chruby ruby-2.6.4' >> ~/.bash_profile
  - &restore-gems
    restore_cache:
      keys:
        - gems-{{ checksum "Gemfile.lock" }}
        - gems-
  - &install-gems
    run:
      name: Bundle install
      command: bundle check || bundle install
      environment:
        BUNDLE_JOBS: 4
        BUNDLE_RETRY: 3
  - &store-gems
    save_cache:
      key: gems-{{ checksum "Gemfile.lock" }}
      paths:
        - vendor/bundle
  - &fetch-xcode-logs
    run:
      name: Getting Xcode activity logs
      command: find $HOME/Library/Developer/Xcode/DerivedData -name '*.xcactivitylog' -exec cp {} $CIRCLE_ARTIFACTS/xcactivitylog \; || true
  - &store-artifacts
    store_artifacts:
      path: /tmp/circleci-artifacts


version: 2
jobs:
  lint:
    <<: *default-config
    steps:
      - *prepare-storage
      - checkout
      - *set-ruby-version
      - *restore-gems
      - *install-gems
      - *store-gems
      - run:
          name: Install SwiftLint
          command: bundle exec rake swiftlint:install
      - run:
          name: Lint source code
          command: bundle exec rake swiftlint:run
      - *store-artifacts

  spm-build:
    <<: *default-config
    steps:
      - *prepare-storage
      - checkout
      - *set-ruby-version
      - *restore-gems
      - *install-gems
      - *store-gems
      - run:
          name: SPM Build
          command: bundle exec rake spm:build
      - *store-artifacts

  xcode-ios-build:
    <<: *default-config
    steps:
      - *prepare-storage
      - checkout
      - *set-ruby-version
      - *restore-gems
      - *install-gems
      - *store-gems
      - run:
          name: Build iOS Framework
          command: bundle exec rake fmk:ios
      - run:
          name: Build iOS Demo
          command: bundle exec rake demo:ios
      - store_test_results:
          path: /tmp/circleci-test-results
      - *fetch-xcode-logs
      - *store-artifacts

  xcode-tvos-build:
    <<: *default-config
    steps:
      - *prepare-storage
      - checkout
      - *set-ruby-version
      - *restore-gems
      - *install-gems
      - *store-gems
      - run:
          name: Build tvOS Framework
          command: bundle exec rake fmk:tvos
      - run:
          name: Build tvOS Demo
          command: bundle exec rake demo:tvos
      - store_test_results:
          path: /tmp/circleci-test-results
      - *fetch-xcode-logs
      - *store-artifacts

  pod-lint:
    <<: *default-config
    steps:
      - *prepare-storage
      - checkout
      - *set-ruby-version
      - *restore-gems
      - *install-gems
      - *store-gems
      - run:
          name: Lint podspec
          command: bundle exec rake pod:lint
      - *store-artifacts

  carthage-build:
    <<: *default-config
    steps:
      - *prepare-storage
      - checkout
      - *set-ruby-version
      - *restore-gems
      - *install-gems
      - *store-gems
      - run:
          name: Install Carthage
          command: bundle exec rake carthage:install
      - run:
          name: Carthage Build
          command: bundle exec rake carthage:build
      - store_test_results:
          path: /tmp/circleci-test-results
      - *fetch-xcode-logs
      - *store-artifacts

workflows:
  version: 2
  check_all_builds:
    jobs:
      - lint
      - xcode-ios-build:
          requires:
            - lint
      - xcode-tvos-build:
          requires:
            - lint
      - spm-build:
          requires:
            - lint
      - carthage-build:
          requires:
            - xcode-ios-build
            - xcode-tvos-build
      - pod-lint:
          requires:
            - spm-build
            - xcode-ios-build
            - xcode-tvos-build
